apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipinfo-webapp-deployment
spec:
  selector:
    matchLabels:
      app: ipinfo-webapp
  template:
    metadata:
      labels:
        app: ipinfo-webapp
    spec:
      containers:
        - name: ipinfo-webapp
          image: peterdavehello/ipinfo.tw
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ipinfo-webapp-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ipinfo-webapp
